# Generated by Django 2.0.2 on 2018-03-20 02:21

from django.db import migrations, models
import django.db.models.deletion
import projects.utils


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0002_auto_20180313_0957'),
    ]

    operations = [
        migrations.CreateModel(
            name='Gallery',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250)),
                ('description', models.TextField(blank=True, null=True)),
                ('date_designed', models.DateField(blank=True, null=True)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Mockup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to=projects.utils.get_gallery_directory)),
                ('date_uploaded', models.DateTimeField(auto_now_add=True)),
                ('gallery', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='projects.Gallery')),
            ],
        ),
    ]
